import { NotificationType, NotificationPriority } from '@prisma/client';
import { NotificationEvent } from './notification-event.enum';

export const NOTIFICATION_EVENT_MAP: Record<
  string,
  {
    type: NotificationType;
    priority: NotificationPriority;
    category: 'coaching' | 'evaluation' | 'cohort' | 'invitation' | 'document' | 'ai' | 'admin';
    requiresEmail: boolean;
  }
> = {
  [NotificationEvent.APPLICATION_SUBMITTED]: {
    type: NotificationType.APPLICATION_SUBMITTED,
    priority: NotificationPriority.MEDIUM,
    category: 'cohort',
    requiresEmail: false,
  },
  [NotificationEvent.APPLICATION_WITHDRAWN]: {
    type: NotificationType.APPLICATION_REJECTED,
    priority: NotificationPriority.LOW,
    category: 'cohort',
    requiresEmail: false,
  },
  [NotificationEvent.INVITATION_SENT]: {
    type: NotificationType.INVITATION_RECEIVED,
    priority: NotificationPriority.HIGH,
    category: 'invitation',
    requiresEmail: true,
  },
  [NotificationEvent.APPLICATION_ACCEPTED]: {
    type: NotificationType.APPLICATION_ACCEPTED,
    priority: NotificationPriority.HIGH,
    category: 'invitation',
    requiresEmail: true,
  },
  [NotificationEvent.APPLICATION_REJECTED]: {
    type: NotificationType.APPLICATION_REJECTED,
    priority: NotificationPriority.MEDIUM,
    category: 'invitation',
    requiresEmail: true,
  },
  [NotificationEvent.INVITATION_ACCEPTED]: {
    type: NotificationType.INVITATION_ACCEPTED,
    priority: NotificationPriority.MEDIUM,
    category: 'invitation',
    requiresEmail: true,
  },
  [NotificationEvent.INVITATION_REJECTED]: {
    type: NotificationType.INVITATION_REJECTED,
    priority: NotificationPriority.LOW,
    category: 'invitation',
    requiresEmail: false,
  },
  [NotificationEvent.MEMBER_JOINED]: {
    type: NotificationType.MEMBER_JOINED,
    priority: NotificationPriority.MEDIUM,
    category: 'cohort',
    requiresEmail: false,
  },
  [NotificationEvent.MEMBER_INVITED]: {
    type: NotificationType.INVITATION_RECEIVED,
    priority: NotificationPriority.MEDIUM,
    category: 'invitation',
    requiresEmail: true,
  },
  [NotificationEvent.MEMBER_UPDATED]: {
    type: NotificationType.MEMBER_JOINED,
    priority: NotificationPriority.LOW,
    category: 'cohort',
    requiresEmail: false,
  },
  [NotificationEvent.MEMBER_LEFT]: {
    type: NotificationType.MEMBER_LEFT,
    priority: NotificationPriority.LOW,
    category: 'cohort',
    requiresEmail: false,
  },
  [NotificationEvent.COHORT_CREATED]: {
    type: NotificationType.COHORT_CREATED,
    priority: NotificationPriority.MEDIUM,
    category: 'cohort',
    requiresEmail: false,
  },
  [NotificationEvent.COHORT_UPDATED]: {
    type: NotificationType.COHORT_UPDATED,
    priority: NotificationPriority.LOW,
    category: 'cohort',
    requiresEmail: false,
  },
  [NotificationEvent.APPLICATION_OPEN]: {
    type: NotificationType.APPLICATION_OPEN,
    priority: NotificationPriority.MEDIUM,
    category: 'cohort',
    requiresEmail: false,
  },
  [NotificationEvent.INCUBATOR_STATUS_CHANGED]: {
    type: NotificationType.COHORT_UPDATED,
    priority: NotificationPriority.MEDIUM,
    category: 'cohort',
    requiresEmail: false,
  },
  [NotificationEvent.PROJECT_CREATED]: {
    type: NotificationType.STEP_COMPLETED,
    priority: NotificationPriority.LOW,
    category: 'coaching',
    requiresEmail: false,
  },
  [NotificationEvent.DOCUMENT_VERIFIED]: {
    type: NotificationType.DOCUMENT_VERIFIED,
    priority: NotificationPriority.HIGH,
    category: 'document',
    requiresEmail: true,
  },
  [NotificationEvent.NEW_EVALUATION]: {
    type: NotificationType.NEW_EVALUATION,
    priority: NotificationPriority.HIGH,
    category: 'evaluation',
    requiresEmail: false,
  },
  [NotificationEvent.COACHING_SCHEDULED]: {
    type: NotificationType.COACHING_SCHEDULED,
    priority: NotificationPriority.MEDIUM,
    category: 'coaching',
    requiresEmail: false,
  },
  [NotificationEvent.DOCUMENT_GENERATED]: {
    type: NotificationType.DOCUMENT_GENERATED,
    priority: NotificationPriority.LOW,
    category: 'document',
    requiresEmail: false,
  },
  [NotificationEvent.DOCUMENT_UPDATED]: {
    type: NotificationType.DOCUMENT_UPDATED,
    priority: NotificationPriority.LOW,
    category: 'document',
    requiresEmail: false,
  },
  [NotificationEvent.AI_RESPONSE_READY]: {
    type: NotificationType.AI_RESPONSE_READY,
    priority: NotificationPriority.LOW,
    category: 'ai',
    requiresEmail: false,
  },
  [NotificationEvent.STEP_COMPLETED]: {
    type: NotificationType.STEP_COMPLETED,
    priority: NotificationPriority.LOW,
    category: 'coaching',
    requiresEmail: false,
  },
  [NotificationEvent.ASSIGNED_AS_COACH]: {
    type: NotificationType.ASSIGNED_AS_COACH,
    priority: NotificationPriority.HIGH,
    category: 'coaching',
    requiresEmail: true,
  },
  [NotificationEvent.ASSIGNED_AS_JURY]: {
    type: NotificationType.ASSIGNED_AS_JURY,
    priority: NotificationPriority.HIGH,
    category: 'evaluation',
    requiresEmail: true,
  },
  [NotificationEvent.EVALUATION_REQUESTED]: {
    type: NotificationType.EVALUATION_REQUESTED,
    priority: NotificationPriority.HIGH,
    category: 'evaluation',
    requiresEmail: false,
  },
  [NotificationEvent.PROJECT_MATCHED]: {
    type: NotificationType.PROJECT_MATCHED,
    priority: NotificationPriority.MEDIUM,
    category: 'coaching',
    requiresEmail: false,
  },
  [NotificationEvent.PROJECT_UNMATCHED]: {
    type: NotificationType.PROJECT_UNMATCHED,
    priority: NotificationPriority.LOW,
    category: 'coaching',
    requiresEmail: false,
  },
  [NotificationEvent.NEW_USER_REGISTERED]: {
    type: NotificationType.NEW_USER_REGISTERED,
    priority: NotificationPriority.LOW,
    category: 'admin',
    requiresEmail: false,
  },
  [NotificationEvent.NEW_INCUBATOR]: {
    type: NotificationType.NEW_INCUBATOR,
    priority: NotificationPriority.MEDIUM,
    category: 'admin',
    requiresEmail: false,
  },
  [NotificationEvent.NEW_EXPERT]: {
    type: NotificationType.NEW_EXPERT,
    priority: NotificationPriority.LOW,
    category: 'admin',
    requiresEmail: false,
  },
  [NotificationEvent.PASSWORD_RESET_REQUESTED]: {
    type: NotificationType.STEP_COMPLETED,
    priority: NotificationPriority.LOW,
    category: 'coaching',
    requiresEmail: false,
  },
  [NotificationEvent.PASSWORD_RESET_COMPLETED]: {
    type: NotificationType.STEP_COMPLETED,
    priority: NotificationPriority.LOW,
    category: 'coaching',
    requiresEmail: false,
  },
  [NotificationEvent.USER_REPORTED]: {
    type: NotificationType.USER_REPORTED,
    priority: NotificationPriority.HIGH,
    category: 'admin',
    requiresEmail: true,
  },
  [NotificationEvent.CRITICAL_ERROR]: {
    type: NotificationType.CRITICAL_ERROR,
    priority: NotificationPriority.CRITICAL,
    category: 'admin',
    requiresEmail: true,
  },
  [NotificationEvent.DOCUMENT_PENDING]: {
    type: NotificationType.DOCUMENT_PENDING,
    priority: NotificationPriority.MEDIUM,
    category: 'document',
    requiresEmail: false,
  },

  // === COACHING & ÉVALUATION (module) ===
  [NotificationEvent.COACHING_SESSION_SCHEDULED]: {
    type: NotificationType.COACHING_SESSION_SCHEDULED,
    priority: NotificationPriority.MEDIUM,
    category: 'coaching',
    requiresEmail: false,
  },
  [NotificationEvent.COACHING_SESSION_UPDATED]: {
    type: NotificationType.COACHING_SESSION_UPDATED,
    priority: NotificationPriority.LOW,
    category: 'coaching',
    requiresEmail: false,
  },
  [NotificationEvent.COACHING_SESSION_CANCELLED]: {
    type: NotificationType.COACHING_SESSION_CANCELLED,
    priority: NotificationPriority.MEDIUM,
    category: 'coaching',
    requiresEmail: false,
  },
  [NotificationEvent.COACHING_SESSION_COMPLETED]: {
    type: NotificationType.COACHING_SESSION_COMPLETED,
    priority: NotificationPriority.MEDIUM,
    category: 'coaching',
    requiresEmail: false,
  },
  [NotificationEvent.COACHING_REPORT_SUBMITTED]: {
    type: NotificationType.COACHING_REPORT_SUBMITTED,
    priority: NotificationPriority.MEDIUM,
    category: 'coaching',
    requiresEmail: false,
  },
  [NotificationEvent.COACHING_ACTION_ASSIGNED]: {
    type: NotificationType.COACHING_ACTION_ASSIGNED,
    priority: NotificationPriority.HIGH,
    category: 'coaching',
    requiresEmail: false,
  },
  [NotificationEvent.COACHING_ACTION_UPDATED]: {
    type: NotificationType.COACHING_ACTION_UPDATED,
    priority: NotificationPriority.LOW,
    category: 'coaching',
    requiresEmail: false,
  },
  [NotificationEvent.COACHING_ACTION_COMPLETED]: {
    type: NotificationType.COACHING_ACTION_COMPLETED,
    priority: NotificationPriority.MEDIUM,
    category: 'coaching',
    requiresEmail: false,
  },
  [NotificationEvent.COACHING_ACTION_DEADLINE_SOON]: {
    type: NotificationType.COACHING_ACTION_DEADLINE_SOON,
    priority: NotificationPriority.HIGH,
    category: 'coaching',
    requiresEmail: false,
  },
  [NotificationEvent.COACHING_ACTION_OVERDUE]: {
    type: NotificationType.COACHING_ACTION_OVERDUE,
    priority: NotificationPriority.HIGH,
    category: 'coaching',
    requiresEmail: false,
  },
  [NotificationEvent.COACHING_RECOMMENDATION_ADDED]: {
    type: NotificationType.COACHING_RECOMMENDATION_ADDED,
    priority: NotificationPriority.MEDIUM,
    category: 'coaching',
    requiresEmail: false,
  },
  [NotificationEvent.COACHING_COMMENT_ADDED]: {
    type: NotificationType.COACHING_COMMENT_ADDED,
    priority: NotificationPriority.LOW,
    category: 'coaching',
    requiresEmail: false,
  },
  [NotificationEvent.COACH_ASSIGNED]: {
    type: NotificationType.COACH_ASSIGNED,
    priority: NotificationPriority.HIGH,
    category: 'coaching',
    requiresEmail: true,
  },
  [NotificationEvent.COACH_REMOVED]: {
    type: NotificationType.COACH_REMOVED,
    priority: NotificationPriority.MEDIUM,
    category: 'coaching',
    requiresEmail: false,
  },
  [NotificationEvent.EVALUATION_AVAILABLE]: {
    type: NotificationType.EVALUATION_AVAILABLE,
    priority: NotificationPriority.HIGH,
    category: 'evaluation',
    requiresEmail: false,
  },
  [NotificationEvent.EVALUATION_SUBMITTED]: {
    type: NotificationType.EVALUATION_SUBMITTED,
    priority: NotificationPriority.MEDIUM,
    category: 'evaluation',
    requiresEmail: false,
  },
  [NotificationEvent.EVALUATION_ALL_COMPLETED]: {
    type: NotificationType.EVALUATION_ALL_COMPLETED,
    priority: NotificationPriority.HIGH,
    category: 'evaluation',
    requiresEmail: false,
  },
  [NotificationEvent.EVALUATION_DEADLINE_SOON]: {
    type: NotificationType.EVALUATION_DEADLINE_SOON,
    priority: NotificationPriority.HIGH,
    category: 'evaluation',
    requiresEmail: false,
  },
  [NotificationEvent.EVALUATION_TEMPLATE_CREATED]: {
    type: NotificationType.EVALUATION_TEMPLATE_CREATED,
    priority: NotificationPriority.LOW,
    category: 'evaluation',
    requiresEmail: false,
  },
  [NotificationEvent.FINAL_DECISION_MADE]: {
    type: NotificationType.FINAL_DECISION_MADE,
    priority: NotificationPriority.CRITICAL,
    category: 'evaluation',
    requiresEmail: true,
  },
  [NotificationEvent.FINAL_DECISION_UPDATED]: {
    type: NotificationType.FINAL_DECISION_UPDATED,
    priority: NotificationPriority.HIGH,
    category: 'evaluation',
    requiresEmail: true,
  },
  [NotificationEvent.FINAL_DECISION_CONDITIONS_ADDED]: {
    type: NotificationType.FINAL_DECISION_CONDITIONS_ADDED,
    priority: NotificationPriority.HIGH,
    category: 'evaluation',
    requiresEmail: true,
  },
  [NotificationEvent.CONDITION_VALIDATED]: {
    type: NotificationType.CONDITION_VALIDATED,
    priority: NotificationPriority.MEDIUM,
    category: 'evaluation',
    requiresEmail: false,
  },
  [NotificationEvent.REEVALUATION_REQUESTED]: {
    type: NotificationType.REEVALUATION_REQUESTED,
    priority: NotificationPriority.HIGH,
    category: 'evaluation',
    requiresEmail: true,
  },
};
