/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        accent: '#1D9E75',
        'accent-mid': '#0F6E56',
        'accent-dark': '#0a4a3a',
        'accent-light': '#E1F5EE',
        surface: '#ffffff',
        'surface-2': '#f8faf9',
        bg: '#F8F9FA',
        border: 'rgba(0,0,0,0.1)',
        'border-2': 'rgba(0,0,0,0.15)',
        text: '#1a1a1a',
        'text-2': '#6b7280',
        'text-3': '#9ca3af',
        'text-4': '#d4d4d8',
        moss: '#1D9E75',
        'moss-light': '#E6F4EF',
        'moss-dark': '#0F6E56',
        cream: '#F8F9FA',
        red: '#E24B4A',
        'red-light': '#FCEBEB',
        'red-dark': '#b91c1c',
        blue: '#378ADD',
        'blue-light': '#E6F1FB',
        'blue-dark': '#1e40af',
        amber: '#c9a84c',
        'amber-light': '#FAEEDA',
        'amber-dark': '#8a6820',
        green: '#10b981',
        purple: '#8b5cf6',
        'purple-light': '#ede9fe',
      },
      fontFamily: {
        sans: ['DM Sans', 'sans-serif'],
        syne: ['Syne', 'sans-serif'],
      },
      boxShadow: {
        card: '0 1px 3px rgba(0,0,0,0.04), 0 1px 2px rgba(0,0,0,0.06)',
        'card-hover': '0 4px 12px rgba(0,0,0,0.05), 0 2px 4px rgba(0,0,0,0.04)',
        elevated: '0 8px 24px rgba(0,0,0,0.06), 0 4px 8px rgba(0,0,0,0.04)',
        modal: '0 20px 60px rgba(0,0,0,0.12), 0 8px 16px rgba(0,0,0,0.06)',
      },
      animation: {
        'slideIn': 'slideIn 0.35s ease forwards',
        'slideUp': 'slideUp 0.35s ease forwards',
        'fadeIn': 'fadeIn 0.3s ease forwards',
        'scaleIn': 'scaleIn 0.25s ease forwards',
      },
    },
  },
  plugins: [],
}
